import { defineField, defineType } from "sanity";

export const postType = defineType({
  name: "post",
  title: "Article",
  type: "document",
  groups: [
    { name: "content", title: "Contenu", default: true },
    { name: "seo", title: "SEO" },
    { name: "ai", title: "IA" },
    { name: "settings", title: "Reglages" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Titre",
      type: "string",
      group: "content",
      validation: (Rule) => Rule.required().min(3).max(140),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slugObject",
      group: "settings",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "excerpt",
      title: "Extrait",
      type: "text",
      rows: 3,
      group: "content",
      validation: (Rule) => Rule.required().max(220),
    }),
    defineField({
      name: "mainImage",
      title: "Image principale",
      type: "imageWithAlt",
      group: "content",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "content",
      title: "Contenu riche",
      type: "richText",
      group: "content",
      validation: (Rule) => Rule.required().min(1),
    }),
    defineField({
      name: "categories",
      title: "Categories",
      type: "array",
      group: "settings",
      of: [{ type: "reference", to: [{ type: "category" }] }],
      validation: (Rule) => Rule.required().min(1),
    }),
    defineField({
      name: "author",
      title: "Auteur",
      type: "reference",
      to: [{ type: "author" }],
      group: "settings",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "publishedAt",
      title: "Date de publication",
      type: "datetime",
      group: "settings",
      initialValue: () => new Date().toISOString(),
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "seo",
      title: "SEO",
      type: "seo",
      group: "seo",
    }),
    defineField({
      name: "sitemapPriority",
      title: "Priorite dans le sitemap",
      type: "string",
      group: "seo",
      initialValue: "0.5",
      description: "Importance relative de cet article dans le sitemap (1.0 = max).",
      options: {
        list: [
          { title: "Tres haute (1.0)", value: "1.0" },
          { title: "Haute (0.8)", value: "0.8" },
          { title: "Normale (0.5)", value: "0.5" },
          { title: "Basse (0.3)", value: "0.3" },
          { title: "Tres basse (0.1)", value: "0.1" },
        ],
        layout: "radio",
      },
    }),
    defineField({
      name: "sitemapChangefreq",
      title: "Frequence de mise a jour (sitemap)",
      type: "string",
      group: "seo",
      initialValue: "weekly",
      options: {
        list: [
          { title: "Toujours (always)", value: "always" },
          { title: "Chaque heure (hourly)", value: "hourly" },
          { title: "Quotidienne (daily)", value: "daily" },
          { title: "Hebdomadaire (weekly)", value: "weekly" },
          { title: "Mensuelle (monthly)", value: "monthly" },
          { title: "Annuelle (yearly)", value: "yearly" },
          { title: "Jamais (never)", value: "never" },
        ],
        layout: "radio",
      },
    }),
    defineField({
      name: "ai",
      title: "IA et donnees structurees",
      type: "aiMetadata",
      group: "ai",
      initialValue: {
        structuredDataType: "Article",
        allowLlmIndexing: true,
      },
    }),
  ],
  orderings: [
    {
      title: "Date de publication (recent d abord)",
      name: "publishedAtDesc",
      by: [{ field: "publishedAt", direction: "desc" }],
    },
  ],
  preview: {
    select: {
      title: "title",
      subtitle: "author.name",
      media: "mainImage.image",
      date: "publishedAt",
    },
    prepare: ({ title, subtitle, media, date }) => ({
      title: title || "Article sans titre",
      subtitle: `${subtitle || "Auteur inconnu"} - ${date ? new Date(date).toLocaleDateString("fr-FR") : "Sans date"}`,
      media,
    }),
  },
});
